import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Apple,
  Bluetooth,
  Camera,
  CarFront,
  CheckCircle,
  CloudFog,
  CupSoda,
  Disc,
  Feather,
  Flashlight,
  Fuel,
  Gauge,
  Hand,
  Lightbulb,
  MapPin,
  Package,
  Radar,
  Radio,
  Settings,
  Shield,
  ShieldPlus,
  Smartphone,
  Snowflake,
  Square,
  Anchor,
  Zap,
  GripHorizontal,
  Sun,
  Usb,
  Users,
  Waves,
  Wrench,
} from "lucide-react";

type FeatureKey = string | null | undefined;

const featureIconMap: Record<string, LucideIcon> = {
  "air conditioning": Snowflake,
  airbags: Shield,
  "alloy wheels": Disc,
  "am/fm radio": Radio,
  "electric windows": Square,
  "android auto": Smartphone,
  "anti-lock brakes": Gauge,
  armrests: Hand,
  "blind spot monitor": Radar,
  bullbar: ShieldPlus,
  "apple carplay": Apple,
  "cd player": Disc,
  "cruise control": Gauge,
  "cup holders": CupSoda,
  "electric mirrors": Square,
  "front fog lamps": CloudFog,
  "leather seats": Feather,
  "led headlights": Lightbulb,
  "parking assist": Radar,
  "parking sensors": Waves,
  "roof rack": Package,
  sidesteps: GripHorizontal,
  spotlight: Flashlight,
  sunroof: Sun,
  "traction control": Activity,
  winch: Anchor,
  "xenon lights": Zap,
  bluetooth: Bluetooth,
  gps: MapPin,
  usb: Usb,
  "usb port": Usb,
  "backup camera": Camera,
  camera: Camera,
  automatic: Settings,
  manual: Wrench,
};

export const detailIcons = {
  location: MapPin,
  seats: Users,
  transmission: Settings,
  fuel: Fuel,
  carType: CarFront,
} satisfies Record<string, LucideIcon>;

export function getFeatureIcon(feature: FeatureKey) {
  if (!feature) return CheckCircle;
  const key = feature.toLowerCase().trim();
  return featureIconMap[key] ?? CheckCircle;
}
