export const ghanaDistrictsByRegion = {
  "Ahafo Region": [
    "Asunafo North",
    "Asunafo South",
    "Asutifi North",
    "Asutifi South",
    "Tano North",
    "Tano South",
  ],
  "Ashanti Region": [
    "Adansi Asokwa",
    "Adansi North",
    "Adansi South",
    "Afigya-Kwabre North",
    "Afigya-Kwabre South",
    "Ahafo-Ano North",
    "Ahafo-Ano South East",
    "Ahafo-Ano South West",
    "Akrofuom",
    "Amansie Central",
    "Amansie South",
    "Amansie West",
    "Asante-Akim Central",
    "Asante-Akim North",
    "Asante-Akim South",
    "Asokore-Mampong",
    "Asokwa",
    "Atwima-Kwanwoma",
    "Atwima-Mponua",
    "Atwima-Nwabiagya",
    "Atwima-Nwabiagya North",
    "Bekwai",
    "Bosome Freho",
    "Bosomtwe",
    "Ejisu",
    "Ejura/Sekyedumase",
    "Juaben",
    "Kumasi",
    "Kwabre East",
    "Kwadaso",
    "Mampong",
    "Obuasi",
    "Obuasi East",
    "Offinso",
    "Offinso North",
    "Oforikrom",
    "Old Tafo",
    "Sekyere Afram Plains",
    "Sekyere Central",
    "Sekyere East",
    "Sekyere Kumawu",
    "Sekyere South",
    "Suame",
  ],
  "Bono East Region": [
    "Atebubu-Amantin",
    "Kintampo North",
    "Kintampo South",
    "Nkoranza North",
    "Nkoranza South",
    "Pru East",
    "Pru West",
    "Sene East",
    "Sene West",
    "Techiman",
    "Techiman North",
  ],
  "Bono Region": [
    "Banda",
    "Berekum East",
    "Berekum West",
    "Dormaa Central",
    "Dormaa East",
    "Dormaa West",
    "Jaman North",
    "Jaman South",
    "Sunyani",
    "Sunyani West",
    "Tain",
    "Wenchi",
  ],
  "Central Region": [
    "Abura/Asebu/Kwamankese",
    "Agona East",
    "Agona West Municipal",
    "Ajumako/Enyan/Essiam",
    "Asikuma Odoben Brakwa",
    "Assin Central",
    "Assin North",
    "Assin South",
    "Awutu Senya East",
    "Awutu Senya West",
    "Cape Coast",
    "Effutu",
    "Ekumfi",
    "Gomoa Central",
    "Gomoa East",
    "Gomoa West",
    "Komenda/Edina/Eguafo/Abirem",
    "Mfantsiman",
    "Twifo Atti Morkwa",
    "Twifo/Hemang/Lower Denkyira",
    "Upper Denkyira East",
    "Upper Denkyira West",
  ],
  "Eastern Region": [
    "Abuakwa North",
    "Abuakwa South",
    "Achiase",
    "Akuapim North",
    "Akuapim South",
    "Akyemansa",
    "Asene Manso Akroso",
    "Asuogyaman",
    "Atiwa East",
    "Atiwa West",
    "Ayensuano",
    "Birim Central",
    "Birim North",
    "Birim South",
    "Denkyembour",
    "Fanteakwa North",
    "Fanteakwa South",
    "Kwaebibirem",
    "Kwahu Afram Plains North",
    "Kwahu Afram Plains South",
    "Kwahu East",
    "Kwahu South",
    "Kwahu West",
    "Lower Manya Krobo",
    "New Juaben North",
    "New Juaben South",
    "Nsawam Adoagyire",
    "Okere",
    "Suhum",
    "Upper Manya Krobo",
    "Upper West Akim",
    "West Akim",
    "Yilo-Krobo",
  ],
  "Greater Accra Region": [
    "Ablekuma Central",
    "Ablekuma North",
    "Ablekuma West",
    "Accra",
    "Ada East",
    "Ada West",
    "Adenta",
    "Ashaiman",
    "Ayawaso Central",
    "Ayawaso East",
    "Ayawaso North",
    "Ayawaso West",
    "Ga Central",
    "Ga East",
    "Ga North",
    "Ga South",
    "Ga West",
    "Korle-Klottey",
    "Kpone-Katamanso",
    "Krowor",
    "La Dade-Kotopon",
    "La-Nkwantanang-Madina",
    "Ledzokuku",
    "Ningo-Prampram",
    "Okaikwei North",
    "Shai-Osudoku",
    "Tema Metropolitan",
    "Tema West",
    "Weija/Gbawe",
  ],
  "North East Region": [
    "Bunkpurugu-Nyakpanduri",
    "Chereponi",
    "East Mamprusi",
    "Mamprugu Moagduri",
    "West Mamprusi",
    "Yunyoo-Nasuan",
  ],
  "Northern Region": [
    "Gushiegu",
    "Karaga",
    "Kpandai",
    "Kumbungu",
    "Mion",
    "Nanton",
    "Nanumba North",
    "Nanumba South",
    "Saboba",
    "Sagnarigu",
    "Savelugu",
    "Tamale Metropolitan",
    "Tatale Sangule",
    "Tolon",
    "Yendi Municipal",
    "Zabzugu",
  ],
  "Oti Region": [
    "Biakoye",
    "Guan District",
    "Jasikan",
    "Kadjeibi",
    "Krachi East",
    "Krachi Nchumuru",
    "Krachi West",
    "Nkwanta North",
    "Nkwanta South",
  ],
  "Savannah Region": [
    "Bole",
    "Central Gonja",
    "East Gonja",
    "North East Gonja",
    "North Gonja",
    "Sawla-Tuna-Kalba",
    "West Gonja",
  ],
  "Upper East Region": [
    "Bawku Municipal",
    "Bawku West",
    "Binduri",
    "Bolgatanga Municipal",
    "Bolgatanga East",
    "Bongo",
    "Builsa North",
    "Builsa South",
    "Garu",
    "Kassena Nankana Municipal",
    "Kassena Nankana West",
    "Nabdam",
    "Pusiga",
    "Talensi",
    "Tempane",
  ],
  "Upper West Region": [
    "Daffiama-Bussie-Issa",
    "Jirapa",
    "Lambussie Karni",
    "Lawra",
    "Nadowli-Kaleo",
    "Nandom",
    "Sissala East",
    "Sissala West",
    "Wa East",
    "Wa Municipal",
    "Wa West",
  ],
  "Volta Region": [
    "Adaklu",
    "Afadzato South",
    "Agotime Ziope",
    "Akatsi North",
    "Akatsi South",
    "Anloga",
    "Central Tongu",
    "Ho Municipal",
    "Ho West",
    "Hohoe Municipal",
    "Keta Municipal",
    "Ketu North Municipal",
    "Ketu South Municipal",
    "Kpando Municipal",
    "North Dayi",
    "North Tongu",
    "South Dayi",
    "South Tongu",
  ],
  "Western North Region": [
    "Aowin",
    "Bia East",
    "Bia West",
    "Bibiani Anhwiaso Bekwai",
    "Bodi",
    "Juaboso",
    "Sefwi Akontombra",
    "Sefwi Wiawso",
    "Suaman",
  ],
  "Western Region": [
    "Ahanta West",
    "Amenfi Central",
    "Amenfi East",
    "Amenfi West",
    "Effia-Kwesimintsim",
    "Ellembelle",
    "Jomoro",
    "Mpohor",
    "Nzema East",
    "Prestea-Huni Valley",
    "Sekondi Takoradi Metropolitan",
    "Shama",
    "Tarkwa-Nsuaem",
    "Wassa East",
  ],
} as const;

export const ghanaDistrictCapitals = {
  "Ablekuma Central": "Lartebiokorshie",
  "Ablekuma North": "Darkuman",
  "Ablekuma West": "Dansoman",
  "Abuakwa North": "Kukurantumi",
  "Abuakwa South": "Kibi",
  "Abura/Asebu/Kwamankese": "Abura-Dunkwa",
  Accra: "Accra",
  Achiase: "Achiase",
  "Ada East": "Ada Foah",
  "Ada West": "Sege",
  Adaklu: "Adaklu Waya",
  "Adansi Asokwa": "Adansi Asokwa",
  "Adansi North": "Fomena",
  "Adansi South": "New Edubiase",
  Adenta: "Adenta",
  "Afadzato South": "Ve Golokwati",
  "Afigya-Kwabre North": "Boamang",
  "Afigya-Kwabre South": "Kodie",
  "Agona East": "Nsaba",
  "Agona West Municipal": "Agona Swedru",
  "Agotime Ziope": "Kpetoe",
  "Ahafo-Ano North": "Tepa",
  "Ahafo-Ano South East": "Adugyama",
  "Ahafo-Ano South West": "Mankranso",
  "Ahanta West": "Agona Nkwanta",
  "Ajumako/Enyan/Essiam": "Ajumako",
  "Akatsi North": "Ave-Dakpa",
  "Akatsi South": "Akatsi",
  Akrofuom: "Akrofuom",
  "Akuapim North": "Akropong",
  "Akuapim South": "Aburi",
  Akyemansa: "Ofoase",
  "Amansie Central": "Jacobu",
  "Amansie South": "Manso Adubia",
  "Amansie West": "Manso Nkwanta",
  "Amenfi Central": "Manso Amenfi",
  "Amenfi East": "Wassa-Akropong",
  "Amenfi West": "Asankragua",
  Anloga: "Anloga",
  Aowin: "Enchi",
  "Asante-Akim Central": "Konongo",
  "Asante-Akim North": "Agogo",
  "Asante-Akim South": "Juaso",
  "Asene Manso Akroso": "Manso",
  Ashaiman: "Ashaiman",
  "Asikuma Odoben Brakwa": "Breman Asikuma",
  "Asokore-Mampong": "Asokore Mampong",
  Asokwa: "Asokwa",
  "Assin Central": "Assin Foso",
  "Assin North": "Assin Bereku",
  "Assin South": "Nsuaem Kyekyewere",
  "Asunafo North": "Goaso",
  "Asunafo South": "Kukuom",
  Asuogyaman: "Atimpoku",
  "Asutifi North": "Kenyasi",
  "Asutifi South": "Hwidiem",
  "Atebubu-Amantin": "Atebubu",
  "Atiwa East": "Anyinam",
  "Atiwa West": "Kwabeng",
  "Atwima-Kwanwoma": "Twedie",
  "Atwima-Mponua": "Nyinahin",
  "Atwima-Nwabiagya": "Nkawie",
  "Atwima-Nwabiagya North": "Barekese",
  "Awutu Senya East": "Kasoa",
  "Awutu Senya West": "Awutu Breku",
  "Ayawaso Central": "Kokomlemle",
  "Ayawaso East": "Nima",
  "Ayawaso North": "Accra New Town",
  "Ayawaso West": "Dzorwulu",
  Ayensuano: "Coaltar",
  Banda: "Banda Ahenkro",
  "Bawku Municipal": "Bawku",
  "Bawku West": "Zebilla",
  Bekwai: "Bekwai",
  "Berekum East": "Berekum",
  "Berekum West": "Jinijini",
  "Bia East": "Sefwi Adabokrom",
  "Bia West": "Essam",
  Biakoye: "Nkonya Ahenkro",
  "Bibiani Anhwiaso Bekwai": "Bibiani",
  Binduri: "Binduri",
  "Birim Central": "Akim Oda",
  "Birim North": "New Abirem",
  "Birim South": "Akim Swedru",
  Bodi: "Bodi",
  Bole: "Bole",
  "Bolgatanga East": "Zuarungu",
  "Bolgatanga Municipal": "Bolgatanga",
  Bongo: "Bongo",
  "Bosome Freho": "Asiwa",
  Bosomtwe: "Kuntanase",
  "Builsa North": "Sandema",
  "Builsa South": "Fumbisi",
  "Bunkpurugu-Nyakpanduri": "Bunkpurugu",
  "Cape Coast": "Cape Coast",
  "Central Gonja": "Buipe",
  "Central Tongu": "Adidome",
  Chereponi: "Chereponi",
  "Daffiama-Bussie-Issa": "Issa",
  Denkyembour: "Akwatia",
  "Dormaa Central": "Dormaa Ahenkro",
  "Dormaa East": "Wamfie",
  "Dormaa West": "Nkrankwanta",
  "East Gonja": "Salaga",
  "East Mamprusi": "Gambaga",
  "Effia-Kwesimintsim": "Effiakuma",
  Effutu: "Winneba",
  Ejisu: "Ejisu",
  "Ejura/Sekyedumase": "Ejura",
  Ekumfi: "Esakyir",
  Ellembelle: "Nkroful",
  "Fanteakwa North": "Begoro",
  "Fanteakwa South": "Osino",
  "Ga Central": "Sowutuom",
  "Ga East": "Abokobi",
  "Ga North": "Amomole",
  "Ga South": "Ngleshie Amanfro",
  "Ga West": "Amasaman",
  Garu: "Garu",
  "Gomoa Central": "Afransi",
  "Gomoa East": "Potsin",
  "Gomoa West": "Apam",
  "Guan District": "Likpe-Mate",
  Gushiegu: "Gushegu",
  "Ho Municipal": "Ho",
  "Ho West": "Dzolokpuita",
  "Hohoe Municipal": "Hohoe",
  "Jaman North": "Sampa",
  "Jaman South": "Drobo",
  Jasikan: "Jasikan",
  Jirapa: "Jirapa",
  Jomoro: "Half Assini",
  Juaben: "Juaben",
  Juaboso: "Juaboso",
  Kadjeibi: "Kadjeibi",
  Karaga: "Karaga",
  "Kassena Nankana Municipal": "Navrongo",
  "Kassena Nankana West": "Paga",
  "Keta Municipal": "Keta",
  "Ketu North Municipal": "Dzodze",
  "Ketu South Municipal": "Denu",
  "Kintampo North": "Kintampo",
  "Kintampo South": "Jema",
  "Komenda/Edina/Eguafo/Abirem": "Elmina",
  "Korle-Klottey": "Osu",
  Kpandai: "Kpandai",
  "Kpando Municipal": "Kpandu",
  "Kpone-Katamanso": "Kpone",
  "Krachi East": "Dambai",
  "Krachi Nchumuru": "Chinderi",
  "Krachi West": "Kete Krachi",
  Krowor: "Nungua",
  Kumasi: "Kumasi",
  Kumbungu: "Kumbungu",
  "Kwabre East": "Mamponteng",
  Kwadaso: "Kwadaso",
  Kwaebibirem: "Kade",
  "Kwahu Afram Plains North": "Donkorkrom",
  "Kwahu Afram Plains South": "Tease",
  "Kwahu East": "Abetifi",
  "Kwahu South": "Mpraeso",
  "Kwahu West": "Nkawkaw",
  "La Dade-Kotopon": "La",
  "La-Nkwantanang-Madina": "Madina",
  "Lambussie Karni": "Lambussie",
  Lawra: "Lawra",
  Ledzokuku: "Teshie",
  "Lower Manya Krobo": "Krobo Odumase",
  Mampong: "Mampong",
  "Mamprugu Moagduri": "Yagaba",
  Mfantsiman: "Saltpond",
  Mion: "Sang",
  Mpohor: "Mpohor",
  Nabdam: "Nangodi",
  "Nadowli-Kaleo": "Nadowli",
  Nandom: "Nandom",
  Nanton: "Nanton",
  "Nanumba North": "Bimbilla",
  "Nanumba South": "Wulensi",
  "New Juaben North": "Effiduase",
  "New Juaben South": "Koforidua",
  "Ningo-Prampram": "Prampram",
  "Nkoranza North": "Busunya",
  "Nkoranza South": "Nkoranza",
  "Nkwanta North": "Kpassa",
  "Nkwanta South": "Nkwanta",
  "North Dayi": "Anfoega",
  "North East Gonja": "Kpalbe",
  "North Gonja": "Daboya",
  "North Tongu": "Battor Dugame",
  "Nsawam Adoagyire": "Nsawam",
  "Nzema East": "Axim",
  Obuasi: "Obuasi",
  "Obuasi East": "Tutuka",
  Offinso: "Offinso",
  "Offinso North": "Akomadan",
  Oforikrom: "Oforikrom",
  "Okaikwei North": "Tesano",
  Okere: "Adukrom",
  "Old Tafo": "Old Tafo",
  "Prestea-Huni Valley": "Bogoso",
  "Pru East": "Yeji",
  "Pru West": "Prang",
  Pusiga: "Pusiga",
  Saboba: "Saboba",
  Sagnarigu: "Sagnarigu",
  Savelugu: "Savelugu",
  "Sawla-Tuna-Kalba": "Sawla",
  "Sefwi Akontombra": "Sefwi Akontombra",
  "Sefwi Wiawso": "Sefwi Wiawso",
  "Sekondi Takoradi Metropolitan": "Sekondi-Takoradi",
  "Sekyere Afram Plains": "Drobonso",
  "Sekyere Central": "Nsuta",
  "Sekyere East": "Effiduase",
  "Sekyere Kumawu": "Kumawu",
  "Sekyere South": "Agona",
  "Sene East": "Kajaji",
  "Sene West": "Kwame Danso",
  "Shai-Osudoku": "Dodowa",
  Shama: "Shama",
  "Sissala East": "Tumu",
  "Sissala West": "Gwollu",
  "South Dayi": "Kpeve",
  "South Tongu": "Sogakope",
  Suaman: "Dadieso",
  Suame: "Suame",
  Suhum: "Suhum, Ghana",
  Sunyani: "Sunyani",
  "Sunyani West": "Odumase",
  Tain: "Nsawkaw",
  Talensi: "Tongo",
  "Tamale Metropolitan": "Tamale",
  "Tano North": "Duayaw Nkwanta",
  "Tano South": "Bechem",
  "Tarkwa-Nsuaem": "Tarkwa",
  "Tatale Sangule": "Tatale",
  Techiman: "Techiman",
  "Techiman North": "Tuobodom",
  "Tema Metropolitan": "Tema",
  "Tema West": "Tema Community 2",
  Tempane: "Tempane",
  Tolon: "Tolon",
  "Twifo Atti Morkwa": "Twifo Praso",
  "Twifo/Hemang/Lower Denkyira": "Hemang",
  "Upper Denkyira East": "Dunkwa-on-Offin",
  "Upper Denkyira West": "Diaso",
  "Upper Manya Krobo": "Asesewa",
  "Upper West Akim": "Adeiso",
  "Wa East": "Funsi",
  "Wa Municipal": "Wa",
  "Wa West": "Wechiau",
  "Wassa East": "Daboase",
  "Weija/Gbawe": "Weija",
  Wenchi: "Wenchi",
  "West Akim": "Asamankese",
  "West Gonja": "Damongo",
  "West Mamprusi": "Walewale",
  "Yendi Municipal": "Yendi",
  "Yilo-Krobo": "Somanya",
  "Yunyoo-Nasuan": "Yunyoo",
  Zabzugu: "Zabzugu",
} as const;

export type GhanaRegion = keyof typeof ghanaDistrictsByRegion;

export type GhanaLocationOption = {
  region: GhanaRegion;
  city: string;
};

export const ghanaRegions = Object.keys(
  ghanaDistrictsByRegion,
) as GhanaRegion[];

export const ghanaLocationOptions: GhanaLocationOption[] = ghanaRegions.flatMap(
  (region) =>
    ghanaDistrictsByRegion[region].map((city) => ({
      region,
      city,
    })),
);
