package com.hayame.app.ui.reference

object AndroidReferenceData {
    const val defaultRegion: String = "Greater Accra Region"

    val regions: List<String> = listOf(
        "Ahafo Region",
        "Ashanti Region",
        "Bono East Region",
        "Bono Region",
        "Central Region",
        "Eastern Region",
        "Greater Accra Region",
        "North East Region",
        "Northern Region",
        "Oti Region",
        "Savannah Region",
        "Upper East Region",
        "Upper West Region",
        "Volta Region",
        "Western North Region",
        "Western Region",
    )

    val districtsByRegion: Map<String, List<String>> = mapOf(
        "Ahafo Region" to listOf(
            "Asunafo North",
            "Asunafo South",
            "Asutifi North",
            "Asutifi South",
            "Tano North",
            "Tano South",
        ),
        "Ashanti Region" to listOf(
            "Adansi Asokwa",
            "Adansi North",
            "Adansi South",
            "Afigya-Kwabre North",
            "Afigya-Kwabre South",
            "Ahafo-Ano North",
            "Ahafo-Ano South East",
            "Ahafo-Ano South West",
            "Akrofuom",
            "Amansie Central",
            "Amansie South",
            "Amansie West",
            "Asante-Akim Central",
            "Asante-Akim North",
            "Asante-Akim South",
            "Asokore-Mampong",
            "Asokwa",
            "Atwima-Kwanwoma",
            "Atwima-Mponua",
            "Atwima-Nwabiagya",
            "Atwima-Nwabiagya North",
            "Bekwai",
            "Bosome Freho",
            "Bosomtwe",
            "Ejisu",
            "Ejura/Sekyedumase",
            "Juaben",
            "Kumasi",
            "Kwabre East",
            "Kwadaso",
            "Mampong",
            "Obuasi",
            "Obuasi East",
            "Offinso",
            "Offinso North",
            "Oforikrom",
            "Old Tafo",
            "Sekyere Afram Plains",
            "Sekyere Central",
            "Sekyere East",
            "Sekyere Kumawu",
            "Sekyere South",
            "Suame",
        ),
        "Bono East Region" to listOf(
            "Atebubu-Amantin",
            "Kintampo North",
            "Kintampo South",
            "Nkoranza North",
            "Nkoranza South",
            "Pru East",
            "Pru West",
            "Sene East",
            "Sene West",
            "Techiman",
            "Techiman North",
        ),
        "Bono Region" to listOf(
            "Banda",
            "Berekum East",
            "Berekum West",
            "Dormaa Central",
            "Dormaa East",
            "Dormaa West",
            "Jaman North",
            "Jaman South",
            "Sunyani",
            "Sunyani West",
            "Tain",
            "Wenchi",
        ),
        "Central Region" to listOf(
            "Abura/Asebu/Kwamankese",
            "Agona East",
            "Agona West Municipal",
            "Ajumako/Enyan/Essiam",
            "Asikuma Odoben Brakwa",
            "Assin Central",
            "Assin North",
            "Assin South",
            "Awutu Senya East",
            "Awutu Senya West",
            "Cape Coast",
            "Effutu",
            "Ekumfi",
            "Gomoa Central",
            "Gomoa East",
            "Gomoa West",
            "Komenda/Edina/Eguafo/Abirem",
            "Mfantsiman",
            "Twifo Atti Morkwa",
            "Twifo/Hemang/Lower Denkyira",
            "Upper Denkyira East",
            "Upper Denkyira West",
        ),
        "Eastern Region" to listOf(
            "Abuakwa North",
            "Abuakwa South",
            "Achiase",
            "Akuapim North",
            "Akuapim South",
            "Akyemansa",
            "Asene Manso Akroso",
            "Asuogyaman",
            "Atiwa East",
            "Atiwa West",
            "Ayensuano",
            "Birim Central",
            "Birim North",
            "Birim South",
            "Denkyembour",
            "Fanteakwa North",
            "Fanteakwa South",
            "Kwaebibirem",
            "Kwahu Afram Plains North",
            "Kwahu Afram Plains South",
            "Kwahu East",
            "Kwahu South",
            "Kwahu West",
            "Lower Manya Krobo",
            "New Juaben North",
            "New Juaben South",
            "Nsawam Adoagyire",
            "Okere",
            "Suhum",
            "Upper Manya Krobo",
            "Upper West Akim",
            "West Akim",
            "Yilo-Krobo",
        ),
        "Greater Accra Region" to listOf(
            "Ablekuma Central",
            "Ablekuma North",
            "Ablekuma West",
            "Accra",
            "Ada East",
            "Ada West",
            "Adenta",
            "Ashaiman",
            "Ayawaso Central",
            "Ayawaso East",
            "Ayawaso North",
            "Ayawaso West",
            "Ga Central",
            "Ga East",
            "Ga North",
            "Ga South",
            "Ga West",
            "Korle-Klottey",
            "Kpone-Katamanso",
            "Krowor",
            "La Dade-Kotopon",
            "La-Nkwantanang-Madina",
            "Ledzokuku-Krowor",
            "Okaikwei North",
            "Shai-Osudoku",
            "Tema Metropolitan",
            "Tema West",
            "Weija/Gbawe",
        ),
        "North East Region" to listOf(
            "Bunkpurugu-Nyakpanduri",
            "Chereponi",
            "East Mamprusi",
            "Mamprugu Moagduri",
            "West Mamprusi",
            "Yunyoo-Nasuan",
        ),
        "Northern Region" to listOf(
            "Gushiegu",
            "Karaga",
            "Kpandai",
            "Kumbungu",
            "Mion",
            "Nanton",
            "Nanumba North",
            "Nanumba South",
            "Saboba",
            "Sagnarigu",
            "Savelugu",
            "Tamale Metropolitan",
            "Tatale Sangule",
            "Tolon",
            "Yendi Municipal",
            "Zabzugu",
        ),
        "Oti Region" to listOf(
            "Biakoye",
            "Guan District",
            "Jasikan",
            "Kadjeibi",
            "Krachi East",
            "Krachi Nchumuru",
            "Krachi West",
            "Nkwanta North",
            "Nkwanta South",
        ),
        "Savannah Region" to listOf(
            "Bole",
            "Central Gonja",
            "East Gonja",
            "North Gonja",
            "Sawla-Tuna-Kalba",
            "West Gonja",
        ),
        "Upper East Region" to listOf(
            "Bawku Municipal",
            "Bawku West",
            "Binduri",
            "Bolgatanga Municipal",
            "Bongo",
            "Builsa North",
            "Builsa South",
            "Garue",
            "Kassena Nankana Municipal",
            "Kassena Nankana West",
            "Nabdam",
            "Pusiga",
            "Talensi",
        ),
        "Upper West Region" to listOf(
            "Daffiama-Bussie-Issa",
            "Jirapa",
            "Lambussie Karni",
            "Lawra",
            "Nadowli-Kaleo",
            "Nandom",
            "Sissala East",
            "Sissala West",
            "Wa East",
            "Wa Municipal",
            "Wa West",
        ),
        "Volta Region" to listOf(
            "Adaklu",
            "Afadzato South",
            "Agotime Ziope",
            "Akatsi North",
            "Akatsi South",
            "Akatsi South District",
            "Anloga District",
            "Central Tongu",
            "Ho Municipal",
            "Ho West",
            "Hohoe Municipal",
            "Keta Municipal",
            "Ketu North Municipal",
            "Ketu South Municipal",
            "Kpando Municipal",
            "North Tongu",
            "South Dayi",
            "South Tongu",
        ),
        "Western North Region" to listOf(
            "Aowin",
            "Bia East",
            "Bia West",
            "Bibiani Anhwiaso Bekwai",
            "Bodi",
            "Juaboso",
            "Sefwi Akontombra",
            "Sefwi Wiawso",
        ),
        "Western Region" to listOf(
            "Ahanta West",
            "Amenfi Central",
            "Amenfi East",
            "Amenfi West",
            "Effia-Kwesimintsim",
            "Ellembelle",
            "Jomoro",
            "Mpohor",
            "Nzema East",
            "Prestea-Huni Valley",
            "Sekondi Takoradi Metropolitan",
            "Shama",
            "Tarkwa-Nsuaem",
            "Wassa East",
        ),
    )

    val carMakes: List<String> = listOf(
        "Acura",
        "Aeolus (Dongfeng Aeolus)",
        "AITO",
        "Alfa Romeo",
        "Aston Martin",
        "Audi",
        "BAIC",
        "BAW",
        "Bentley",
        "BMW",
        "Buick",
        "BYD",
        "Cadillac",
        "Changan",
        "Chery",
        "Chevrolet",
        "Chrysler",
        "Citroën",
        "Daewoo",
        "Daihatsu",
        "Deepal (Changan Deepal)",
        "Denza",
        "Dodge",
        "Dongfeng",
        "Fiat",
        "Ford",
        "Foton",
        "GAC",
        "Geely",
        "Genesis",
        "GMC",
        "Great Wall",
        "Haval",
        "Honda",
        "Hozon (Neta)",
        "Hummer",
        "Hyundai",
        "Infiniti",
        "Isuzu",
        "JAC",
        "Jaguar",
        "Jeep",
        "Jetour",
        "JMC",
        "Kia",
        "King Long",
        "Lamborghini",
        "Land Rover",
        "Leapmotor",
        "Lexus",
        "Li Auto",
        "Lincoln",
        "Luxgen",
        "Maruti Suzuki",
        "Maserati",
        "Mazda",
        "Mercedes-Benz",
        "MG",
        "Mini",
        "Mitsubishi",
        "Nio",
        "Nissan",
        "Opel",
        "Other Make",
        "Peugeot",
        "Pontiac",
        "Porsche",
        "RAM",
        "Renault",
        "Renault Samsung",
        "Roewe",
        "Rolls-Royce",
        "Rover",
        "Rox Motor",
        "Samsung (older badge)",
        "Sany",
        "Saturn",
        "Scion",
        "Skoda",
        "SsangYong",
        "Subaru",
        "Suzuki",
        "Tata",
        "Tesla",
        "Toyota",
        "Volkswagen",
        "Volvo",
        "Wuling",
        "XPeng",
        "Zotye",
        "ZX Auto",
    )

    val carModelsByMake: Map<String, List<String>> = mapOf(
        "Acura" to listOf(
            "ILX",
            "MDX",
            "RDX",
            "TL",
            "TLX",
            "TSX",
        ),
        "Aeolus (Dongfeng Aeolus)" to listOf(
            "AX7",
            "Mage",
            "Shine",
            "Yixuan",
        ),
        "AITO" to listOf(
            "M5",
            "M7",
            "M9",
        ),
        "Alfa Romeo" to listOf(
            "Giulia",
            "Giulietta",
            "Stelvio",
        ),
        "Aston Martin" to listOf(
            "DB9/DB11",
            "Rapide",
            "Vantage",
        ),
        "Audi" to listOf(
            "A3",
            "A4",
            "A6",
            "A8",
            "Q3",
            "Q5",
            "Q7",
            "Q8",
        ),
        "BAIC" to listOf(
            "BJ40",
            "BJ80",
            "D20",
            "X25",
            "X35",
            "X55",
        ),
        "BAW" to listOf(
            "Beijing 212",
            "BJ series",
        ),
        "Bentley" to listOf(
            "Bentayga",
            "Continental GT",
            "Flying Spur",
        ),
        "BMW" to listOf(
            "1-Series",
            "3-Series",
            "5-Series",
            "7-Series",
            "X1",
            "X3",
            "X5",
            "X6",
            "X7",
        ),
        "Buick" to listOf(
            "Enclave",
            "Encore",
            "LaCrosse",
            "Regal",
        ),
        "BYD" to listOf(
            "Dolphin",
            "F3",
            "Qin",
            "Seal",
            "Song",
            "Tang",
            "Yuan/Atto 3",
        ),
        "Cadillac" to listOf(
            "ATS",
            "CTS",
            "Escalade",
            "SRX",
            "XT5",
        ),
        "Changan" to listOf(
            "Alsvin",
            "CS35",
            "CS55",
            "CS75",
            "Eado",
            "Hunter",
            "UNI-K",
            "UNI-T",
        ),
        "Chery" to listOf(
            "Arrizo 5",
            "Tiggo 2/3/4/7/8",
        ),
        "Chevrolet" to listOf(
            "Aveo",
            "Camaro",
            "Cruze",
            "Equinox",
            "Impala",
            "Malibu",
            "Silverado",
            "Spark",
            "Suburban",
            "Tahoe",
            "Traverse",
        ),
        "Chrysler" to listOf(
            "300",
            "Pacifica",
            "Town & Country",
        ),
        "Citroën" to listOf(
            "Berlingo",
            "C3",
            "C4",
            "C5",
        ),
        "Daewoo" to listOf(
            "Lanos",
            "Leganza",
            "Matiz",
            "Nubira",
        ),
        "Daihatsu" to listOf(
            "Boon/Sirion",
            "Cuore",
            "Hijet",
            "Mira",
            "Tanto",
            "Terios",
        ),
        "Deepal (Changan Deepal)" to listOf(
            "L07",
            "S07",
        ),
        "Denza" to listOf(
            "D9",
            "N7/N8",
        ),
        "Dodge" to listOf(
            "Challenger",
            "Charger",
            "Durango",
            "Grand Caravan",
            "Journey",
        ),
        "Dongfeng" to listOf(
            "EX1 EV",
            "Glory series",
            "Lingzhi",
            "Rich",
        ),
        "Fiat" to listOf(
            "500",
            "Punto",
            "Tipo",
        ),
        "Ford" to listOf(
            "EcoSport",
            "Edge",
            "Escape",
            "Everest",
            "Expedition",
            "Explorer",
            "F-150",
            "Fiesta",
            "Focus",
            "Fusion",
            "Mondeo",
            "Ranger",
            "Transit",
        ),
        "Foton" to listOf(
            "Tunland",
            "View/Toano",
        ),
        "GAC" to listOf(
            "GN8/GM8",
            "GS3",
            "GS4",
            "GS5",
        ),
        "Geely" to listOf(
            "Coolray",
            "Emgrand",
            "GX3",
            "Okavango/Azal",
        ),
        "Genesis" to listOf(
            "G70",
            "G80",
            "G90",
            "GV70",
            "GV80",
        ),
        "GMC" to listOf(
            "Acadia",
            "Sierra",
            "Terrain",
            "Yukon",
        ),
        "Great Wall" to listOf(
            "Hover/Haval older",
            "Steed",
            "Wingle",
        ),
        "Haval" to listOf(
            "H2",
            "H6",
            "H9",
            "Jolion",
        ),
        "Honda" to listOf(
            "Accord",
            "City",
            "Civic",
            "CR-V",
            "Crosstour",
            "Fit/Jazz",
            "HR-V",
            "Insight",
            "Odyssey",
            "Pilot",
            "Ridgeline",
        ),
        "Hozon (Neta)" to listOf(
            "Neta Aya",
            "Neta U",
            "Neta V",
        ),
        "Hummer" to listOf(
            "H2",
            "H3",
        ),
        "Hyundai" to listOf(
            "Accent",
            "Elantra/Avante",
            "H1/Starex",
            "i10",
            "i20",
            "Kona",
            "Palisade",
            "Santa Fe",
            "Sonata",
            "Tucson/ix35",
        ),
        "Infiniti" to listOf(
            "FX35/FX50",
            "G35/G37",
            "Q50",
            "QX60",
            "QX70",
            "QX80",
        ),
        "Isuzu" to listOf(
            "D-Max",
            "MU-X",
            "Trooper",
        ),
        "JAC" to listOf(
            "J3",
            "J5",
            "S2",
            "S3",
            "T6",
        ),
        "Jaguar" to listOf(
            "E-Pace",
            "F-Pace",
            "XE",
            "XF",
            "XJ",
        ),
        "Jeep" to listOf(
            "Cherokee",
            "Compass",
            "Grand Cherokee",
            "Renegade",
            "Wrangler",
        ),
        "Jetour" to listOf(
            "Dashing",
            "T2/Traveller",
            "X70",
            "X90",
        ),
        "JMC" to listOf(
            "Carrying/van models",
            "Vigus",
        ),
        "Kia" to listOf(
            "Bongo",
            "Carnival/Sedona",
            "Cerato/Forte",
            "K2700/K3000",
            "Optima/K5",
            "Picanto/Morning",
            "Rio",
            "Sorento",
            "Soul",
            "Sportage",
            "Telluride",
        ),
        "King Long" to listOf(
            "Coaster/Hiace-style buses",
        ),
        "Lamborghini" to listOf(
            "Aventador",
            "Huracán",
            "Urus",
        ),
        "Land Rover" to listOf(
            "Defender",
            "Discovery",
            "Discovery Sport",
            "Evoque",
            "Freelander",
            "Range Rover",
            "Range Rover Sport",
            "Velar",
        ),
        "Leapmotor" to listOf(
            "C01",
            "C10",
            "C11",
            "T03",
        ),
        "Lexus" to listOf(
            "ES",
            "GS",
            "GX",
            "IS",
            "LS",
            "LX",
            "NX",
            "RX (RX330/RX350/RX450h)",
            "UX",
        ),
        "Li Auto" to listOf(
            "L7",
            "L8",
            "L9",
        ),
        "Lincoln" to listOf(
            "Aviator",
            "MKS",
            "MKZ",
            "Nautilus",
            "Navigator",
        ),
        "Luxgen" to listOf(
            "U6",
            "U7",
        ),
        "Maruti Suzuki" to listOf(
            "Alto",
            "Swift",
        ),
        "Maserati" to listOf(
            "Ghibli",
            "Levante",
            "Quattroporte",
        ),
        "Mazda" to listOf(
            "Atenza/Mazda6",
            "Axela/Mazda3",
            "BT-50",
            "CX-3",
            "CX-5",
            "CX-7",
            "CX-9",
            "Demio/Mazda2",
        ),
        "Mercedes-Benz" to listOf(
            "A-Class",
            "B-Class",
            "C-Class (C180/C200/C300)",
            "CLA",
            "CLS",
            "E-Class (E200/E300/E350)",
            "G-Class",
            "GLA",
            "GLB",
            "GLC",
            "GLE",
            "GLK",
            "GLS",
            "ML/GLE (older ML)",
            "S-Class",
            "Sprinter",
            "Vito",
        ),
        "MG" to listOf(
            "HS",
            "MG5",
            "MG6",
            "RX5",
            "ZS",
        ),
        "Mini" to listOf(
            "Clubman",
            "Cooper",
            "Countryman",
        ),
        "Mitsubishi" to listOf(
            "ASX/RVR",
            "Eclipse Cross",
            "Galant",
            "L200",
            "Lancer",
            "Outlander",
            "Pajero",
            "Pajero Sport",
        ),
        "Nio" to listOf(
            "ES6/EL6",
            "ES8",
            "ET5",
            "ET7",
        ),
        "Nissan" to listOf(
            "Altima",
            "Armada",
            "Juke",
            "Kicks",
            "March/Micra",
            "Maxima",
            "Murano",
            "Navara/Frontier",
            "Note",
            "NP300",
            "Pathfinder",
            "Patrol",
            "Qashqai/Dualis",
            "Rogue",
            "Sentra",
            "Sunny/Almera",
            "X-Trail",
        ),
        "Opel" to listOf(
            "Astra",
            "Corsa",
            "Insignia",
            "Vectra",
            "Zafira",
        ),
        "Other Make" to listOf(
            "Other",
        ),
        "Peugeot" to listOf(
            "2008",
            "206",
            "207",
            "3008",
            "301",
            "306",
            "307",
            "308",
            "407",
            "5008",
            "508",
        ),
        "Pontiac" to listOf(
            "G6",
            "Grand Prix",
            "Vibe",
        ),
        "Porsche" to listOf(
            "911",
            "Cayenne",
            "Macan",
            "Panamera",
        ),
        "RAM" to listOf(
            "1500",
            "2500",
        ),
        "Renault" to listOf(
            "Clio",
            "Duster",
            "Koleos",
            "Logan",
            "Megane",
        ),
        "Renault Samsung" to listOf(
            "QM5/QM6",
            "SM3",
            "SM5",
        ),
        "Roewe" to listOf(
            "i5",
            "RX5",
        ),
        "Rolls-Royce" to listOf(
            "Cullinan",
            "Ghost",
            "Phantom",
            "Wraith",
        ),
        "Rover" to listOf(
            "25/45/75",
            "Mini-era Rover variants",
        ),
        "Rox Motor" to listOf(
            "Polar Stone 01 (ROX 01)",
        ),
        "Samsung (older badge)" to listOf(
            "SM models",
        ),
        "Sany" to listOf(
            "Commercial trucks/equipment",
        ),
        "Saturn" to listOf(
            "Ion",
            "Vue",
        ),
        "Scion" to listOf(
            "FR-S",
            "tC",
            "xA",
            "xB",
        ),
        "Skoda" to listOf(
            "Fabia",
            "Kodiaq",
            "Octavia",
            "Superb",
        ),
        "SsangYong" to listOf(
            "Actyon",
            "Korando",
            "Rexton",
            "Tivoli",
        ),
        "Subaru" to listOf(
            "Forester",
            "Impreza",
            "Legacy",
            "Outback",
            "XV/Crosstrek",
        ),
        "Suzuki" to listOf(
            "Alto",
            "Celerio",
            "Jimny",
            "Swift",
            "SX4",
            "Vitara",
        ),
        "Tata" to listOf(
            "Safari",
            "Xenon",
        ),
        "Tesla" to listOf(
            "Model 3",
            "Model S",
            "Model X",
            "Model Y",
        ),
        "Toyota" to listOf(
            "4Runner",
            "Allion",
            "Alphard/Vellfire",
            "Aqua",
            "Avalon",
            "C-HR",
            "Camry",
            "Corolla",
            "Crown",
            "Fortuner",
            "HiAce",
            "Highlander",
            "Hilux",
            "IST",
            "Land Cruiser",
            "Land Cruiser Prado",
            "Mark X",
            "Noah",
            "Passo",
            "Premio",
            "Prius",
            "Ractis",
            "RAV4",
            "Sequoia",
            "Sienta",
            "Tacoma",
            "Tundra",
            "Vitz/Yaris",
            "Voxy",
            "Wish",
        ),
        "Volkswagen" to listOf(
            "Amarok",
            "Golf",
            "Jetta",
            "Passat",
            "Polo",
            "Tiguan",
            "Touareg",
            "Transporter",
        ),
        "Volvo" to listOf(
            "S60",
            "S80",
            "V60",
            "XC60",
            "XC90",
        ),
        "Wuling" to listOf(
            "Almaz",
            "Mini EV",
            "vans",
        ),
        "XPeng" to listOf(
            "G3",
            "G6",
            "P5",
            "P7",
        ),
        "Zotye" to listOf(
            "T600",
            "Z100",
        ),
        "ZX Auto" to listOf(
            "Grand Tiger",
            "Terralord",
        ),
    )

    val carTypes: List<String> = listOf("SUV", "Sedan", "Hatchback", "Pickup", "Luxury", "Van")
    val transmissions: List<String> = listOf("Automatic", "Manual")
    val fuels: List<String> = listOf("Petrol", "Diesel", "Hybrid", "Electric")

    fun regionsIncluding(preferred: String?): List<String> {
        val value = normalizedRegion(preferred.orEmpty())
        if (value.isBlank()) return regions
        return if (regions.any { it.equals(value, ignoreCase = true) }) regions else listOf(value) + regions
    }

    fun citiesFor(region: String, preferred: String? = null): List<String> {
        val canonical = region.trim().takeIf { it.isNotBlank() }?.let(::normalizedRegion).orEmpty()
        val values = if (canonical.isBlank()) {
            districtsByRegion.values.flatten().distinct().sortedWith(String.CASE_INSENSITIVE_ORDER)
        } else {
            districtsByRegion[canonical].orEmpty()
        }.toMutableList()
        val preferredCity = preferred.orEmpty().trim()
        if (preferredCity.isNotBlank() && values.none { it.equals(preferredCity, ignoreCase = true) }) values.add(0, preferredCity)
        if (values.isEmpty()) values.add(preferredCity.ifBlank { "Accra" })
        return values
    }

    fun makesIncluding(preferred: String?): List<String> {
        val value = normalizedMake(preferred.orEmpty())
        if (value.isBlank()) return carMakes
        return if (carMakes.any { it.equals(value, ignoreCase = true) }) carMakes else listOf(value) + carMakes
    }

    fun modelsFor(make: String, preferred: String? = null): List<String> {
        val values = carModelsByMake[normalizedMake(make)].orEmpty().toMutableList()
        val preferredModel = preferred.orEmpty().trim()
        if (preferredModel.isNotBlank() && values.none { it.equals(preferredModel, ignoreCase = true) }) values.add(0, preferredModel)
        return values
    }

    fun normalizedRegion(raw: String): String {
        val trimmed = raw.trim()
        if (trimmed.isBlank()) return defaultRegion
        return regions.firstOrNull { it.equals(trimmed, ignoreCase = true) } ?: trimmed
    }

    fun normalizedMake(raw: String): String {
        val trimmed = raw.trim()
        if (trimmed.isBlank()) return ""
        return carMakes.firstOrNull { it.equals(trimmed, ignoreCase = true) } ?: trimmed
    }
}
